import "oaidl.idl";
import "ocidl.idl";

[
  uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B0),
  version(1.0)
]
library HTTPD
{
  //////////////////////////////////////////////////////////////////////////
  //
  // Forward declares
  //
  interface IServer;
  interface ISite;
  interface ISites;
  interface IRequest;
  interface IResponse;

  //////////////////////////////////////////////////////////////////////////
  //
  // IServer interface
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B1),
    version(1.0),
  ]
  interface IServer : IDispatch
  {
    [helpstring("Get logfile"), propget]
    HRESULT Logfile([out, retval] BSTR* filename);

    [helpstring("Set logfile"), propput]
    HRESULT Logfile([in] BSTR filename);

    [helpstring("Retrieve sites collection"), propget]
    HRESULT Sites([out, retval] ISites** sites);

    [helpstring("Retrieve a site by name")]
    HRESULT GetSite([in] BSTR name, [out, retval] ISite** site);

    [helpstring("Add a new site to the server")]
    HRESULT AddSite([in] BSTR name, [out, retval] ISite** site);

    [helpstring("Remove a site from the server")]
    HRESULT RemoveSite([in] BSTR name);

    [helpstring("Start the server")]
    HRESULT Start();

    [helpstring("Stop the server")]
    HRESULT Stop();
  }

  //
  // Server class
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B2),
    version(1.0),
    appobject
  ]
  coclass Server
  {
    dispinterface IServer;
  }

  //////////////////////////////////////////////////////////////////////////
  //
  // ISite interface
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B3),
    version(1.0)
  ]
  interface ISite : IDispatch
  {
    [helpstring("Site name"), propget]
    HRESULT Name([out, retval] BSTR* name);

    [helpstring("Site root"), propget]
    HRESULT Root([out, retval] BSTR* root);

    [helpstring("Site root"), propput]
    HRESULT Root([in] BSTR root);

    [helpstring("Add alias for site")]
    HRESULT AddAlias([in]BSTR name, [in] int port);

    [helpstring("Add a mime type to the site")]
    HRESULT AddMimeType([in] BSTR extension, [in] BSTR mimetype);

    [helpstring("Add a default document to the site")]
    HRESULT AddDefaultDocument([in] BSTR document);
  }

  //
  // Site class
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B4),
    version(1.0)
  ]
  coclass Site
  {
    dispinterface ISite;
  }

  //////////////////////////////////////////////////////////////////////////
  //
  // ISites interface
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2B5),
    version(1.0)
  ]
  interface ISites : IDispatch
  {
    [helpstring("Retrieve the enumerator"), id(DISPID_NEWENUM), propget]
    HRESULT _NewEnum([out, retval] IUnknown** ppUnk);

    [helpstring("Retrieve a site item"), id(DISPID_VALUE), propget]
    HRESULT Item([in] BSTR name, [out, retval] ISite** pSite);

    [helpstring("Retrieve the number of sites"), propget]
    HRESULT Count([out, retval] long* pVal);

    [helpstring("Add a new site")]
    HRESULT Add([in] BSTR name, [out, retval] ISite** pSite);
  }

  //////////////////////////////////////////////////////////////////////////
  //
  // IRequest interface
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2BA),
    version(1.0)
  ]
  interface IRequest : IDispatch
  {
  }

  //
  // Request class
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2BB),
    version(1.0)
  ]
  coclass Request
  {
    dispinterface IRequest;
  }

  //////////////////////////////////////////////////////////////////////////
  //
  // IResponse interface
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2BC),
    version(1.0)
  ]
  interface IResponse : IDispatch
  {
    [helpstring("Retrieve a response header")]
    HRESULT GetHeader([in] BSTR name, [out, retval] BSTR* value);

    [helpstring("Set a response header")]
    HRESULT SetHeader([in] BSTR name, [in] BSTR value);

    [helpstring("Send response headers")]
    HRESULT SendHeaders();

    [helpstring("Get buffering state"), propget]
    HRESULT Buffer([out, retval] VARIANT_BOOL* result);
    
    [helpstring("Set buffering state"), propput]
    HRESULT Buffer([in] VARIANT_BOOL value);

    [helpstring("Flush output buffer")]
    HRESULT Flush();

    [helpstring("Send response data")]
    HRESULT Send([in] void* data, [in] int length);
  }

  //
  // Response class
  //
  [
    uuid(F1AF728E-F8BA-481e-B567-84FDFA05B2BD),
    version(1.0)
  ]
  coclass Response
  {
    dispinterface IResponse;
  }

}
